### ISSUE TITLE
Connection error while trying to join group; [sync_group] Timed out while waiting for response

### ISSUE THREAD

**Issue by cintrzyk** [phobos/phobos#130]
### Description
For `max_concurrency: 1` everything works fine, but when I change the value to the number greater than 1 like 5, then starting listeners often crushes with connection errors 🤔  
On the screenshot below you can notice an infinite loop of errors when a consumer tries to join the group.
![image](https://user-images.githubusercontent.com/494720/90627508-53233780-e21c-11ea-84d7-3ecb93d57a74.png)

### How to recreate?
To recreate the issue I have created a sample Rails app with configured Phobos:
https://github.com/cintrzyk/rails-phobos-connection-error

the whole configurations comes to:
```rb 
# config/initializers/phobos.rb
Phobos.configure('config/phobos.yml')
```
```yaml
# config/phobos.yml
listeners:
  - handler: DummyHandler
    topic: test-topic
    group_id: test-1
    max_concurrency: 5
```
```rb
# phobos_boot.rb
require_relative './config/environment'
```

finally Phobos process is started:
```rb
phobos start
```

...and that's it. It might work just fine for you by the first time but please stop & start the Phobos process again and eventually you will have it ;)
