### ISSUE TITLE
Custom Handler is not loading

### ISSUE THREAD

**Issue by codaksh001** [phobos/phobos#168]
After installing Phobos when I try to start its server I am getting the below error
I have configured everything as mentioned in the gem **Readme** document

```
[2024-03-18T18:20:59:243+0530Z] INFO  -- Phobos : <Hash> {:message=>"Phobos configured", :env=>"N/A"}
[2024-03-18T18:20:59:249+0530Z] ERROR -- Phobos::CLI : <Hash> {:message=>"Handler 'Phobos::MyHandler' not defined"}
[2024-03-18T18:20:59:249+0530Z] ERROR -- Phobos::CLI : <Hash> {:message=>"Handler 'Phobos::MyHandler' not defined"}
```
Below is my gem configuration

Ruby Version - `2.7.6`
Rails Version - `6.1.7.5`
phobos Version - `2.1.6`

Below is my file configuration

**Phobos yml file**
```
##config/phobos.yml

logger:
  # Optional log file, set to false or remove to disable it
  file: log/phobos.log
  # Optional output format for stdout, default is false (human readable).
  # Set to true to enable json output.
  stdout_json: false
  level: info
  # Comment the block to disable ruby-kafka logs
  ruby_kafka:
    level: error

kafka:
  # identifier for this application
  client_id: phobos_test
  # list of brokers used to initialize the client ("port:protocol")
  seed_brokers:
    - localhost:9092

consumer:
  # number of seconds after which, if a client hasn't contacted the Kafka cluster,
  # it will be kicked out of the group
  session_timeout: 30
  # interval between offset commits, in seconds
  offset_commit_interval: 10
  # number of messages that can be processed before their offsets are committed.
  # If zero, offset commits are not triggered by message processing
  offset_commit_threshold: 0
  # the time period that committed offsets will be retained, in seconds. Defaults to the broker setting.
  offset_retention_time:
  # interval between heartbeats; must be less than the session window
  heartbeat_interval: 10
  # kafka here supports the same parameters as the top-level, allowing custom connection
  # configuration details for consumers
  kafka:
    connect_timeout: 130

backoff:
  min_ms: 1000
  max_ms: 60000

listeners:
  - handler: Phobos::EchoHandler
    topic: test
    # id of the group that the consumer should join
    group_id: test-1
    delivery: batch
    # Use this if custom backoff is required for a listener
    backoff:
      min_ms: 500
      max_ms: 10000
  - handler: Phobos::MyHandler
    topic: test1
    # id of the group that the consumer should join
    group_id: test-2
    backoff:
      min_ms: 500
      max_ms: 10000
    delivery: batch   
``` 
**Phobos boot file**
```
##phobos_boot

# Use this file to load your code
puts <<~ART
  ______ _           _
  | ___ \\ |         | |
  | |_/ / |__   ___ | |__   ___  ___
  |  __/| '_ \\ / _ \\| '_ \\ / _ \\/ __|
  | |   | | | | (_) | |_) | (_) \\__ \\
  \\_|   |_| |_|\\___/|_.__/ \\___/|___/
ART
puts "
phobos_boot.rb - find this file at #{File.expand_path(__FILE__)}

"

```

**Executer file**

```
## config/initializer/phobos.rb

Phobos.configure('config/phobos.yml')
executor = Phobos::Executor.new
executor.start
executor.stop
```

**Consumer file**

```
## app/phobos/echo_handler.rb
module Phobos
  class EchoHandler
    include Phobos::Handler

    def consume(payload, metadata)
      puts metadata
      puts payload
    end
  end
end
```

```
## app/phobos/my_handler.rb
module Phobos
  class MyHandler
    include Phobos::Handler

    def consume(payload, metadata)
      puts metadata
      puts payload
    end
  end
end
```

Echohandler class is working fine but Myhandler class is giving error
How can I create custom file to act as consumer like Myhandler
Please suggest.
